/* Generated By:JavaCC: Do not edit this line. MiniLenguajeConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniLenguajeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tCOMENT = 8;
  /** RegularExpression Id. */
  int tCLASE = 9;
  /** RegularExpression Id. */
  int tMETODO = 10;
  /** RegularExpression Id. */
  int tPROGRAMA = 11;
  /** RegularExpression Id. */
  int tVAR = 12;
  /** RegularExpression Id. */
  int tAND = 13;
  /** RegularExpression Id. */
  int tOR = 14;
  /** RegularExpression Id. */
  int tNOT = 15;
  /** RegularExpression Id. */
  int tPRINCIPIO = 16;
  /** RegularExpression Id. */
  int tFIN = 17;
  /** RegularExpression Id. */
  int tSI = 18;
  /** RegularExpression Id. */
  int tENT = 19;
  /** RegularExpression Id. */
  int tSI_NO = 20;
  /** RegularExpression Id. */
  int tFSI = 21;
  /** RegularExpression Id. */
  int tMQ = 22;
  /** RegularExpression Id. */
  int tFMQ = 23;
  /** RegularExpression Id. */
  int tESCRIBIR = 24;
  /** RegularExpression Id. */
  int tLEER = 25;
  /** RegularExpression Id. */
  int tMOD = 26;
  /** RegularExpression Id. */
  int tTRUE = 27;
  /** RegularExpression Id. */
  int tFALSE = 28;
  /** RegularExpression Id. */
  int tENTACAR = 29;
  /** RegularExpression Id. */
  int tCARAENT = 30;
  /** RegularExpression Id. */
  int tACCION = 31;
  /** RegularExpression Id. */
  int tVAL = 32;
  /** RegularExpression Id. */
  int tREF = 33;
  /** RegularExpression Id. */
  int tENTERO = 34;
  /** RegularExpression Id. */
  int tDECIMAL = 35;
  /** RegularExpression Id. */
  int tBOOLEANO = 36;
  /** RegularExpression Id. */
  int tCARACTER = 37;
  /** RegularExpression Id. */
  int tLLAVE_IZQ = 38;
  /** RegularExpression Id. */
  int tLLAVE_DCHA = 39;
  /** RegularExpression Id. */
  int tPARENTESIS_IZQ = 40;
  /** RegularExpression Id. */
  int tPARENTESIS_DCHA = 41;
  /** RegularExpression Id. */
  int tCORCHETE_IZQ = 42;
  /** RegularExpression Id. */
  int tCORCHETE_DCHA = 43;
  /** RegularExpression Id. */
  int tOPAS = 44;
  /** RegularExpression Id. */
  int tIGUAL = 45;
  /** RegularExpression Id. */
  int tFIN_SENTENCIA = 46;
  /** RegularExpression Id. */
  int tCOMA = 47;
  /** RegularExpression Id. */
  int tMAS = 48;
  /** RegularExpression Id. */
  int tMENOS = 49;
  /** RegularExpression Id. */
  int tPOR = 50;
  /** RegularExpression Id. */
  int tDIV = 51;
  /** RegularExpression Id. */
  int tMAI = 52;
  /** RegularExpression Id. */
  int tMEI = 53;
  /** RegularExpression Id. */
  int tNI = 54;
  /** RegularExpression Id. */
  int tMAYOR = 55;
  /** RegularExpression Id. */
  int tMENOR = 56;
  /** RegularExpression Id. */
  int tCHAR = 59;
  /** RegularExpression Id. */
  int tSTRING = 60;
  /** RegularExpression Id. */
  int tIDENTIFICADOR = 61;
  /** RegularExpression Id. */
  int tVALOR_ENTERO = 62;
  /** RegularExpression Id. */
  int tVALOR_DECIMAL = 63;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMENT = 1;
  /** Lexical state. */
  int STRING = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"%%\"",
    "\"%%\"",
    "<tCOMENT>",
    "\"clase\"",
    "\"metodo\"",
    "\"programa\"",
    "\"var\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"principio\"",
    "\"fin\"",
    "\"si\"",
    "\"ent\"",
    "\"si_no\"",
    "\"fsi\"",
    "\"mq\"",
    "\"fmq\"",
    "\"escribir\"",
    "\"leer\"",
    "\"mod\"",
    "\"true\"",
    "\"false\"",
    "\"entacar\"",
    "\"caraent\"",
    "\"accion\"",
    "\"val\"",
    "\"ref\"",
    "\"entero\"",
    "\"decimal\"",
    "\"booleano\"",
    "\"caracter\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\":=\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "<tDIV>",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\">\"",
    "\"<\"",
    "\"\\\"\"",
    "\"\\\"\"",
    "<tCHAR>",
    "<tSTRING>",
    "<tIDENTIFICADOR>",
    "<tVALOR_ENTERO>",
    "<tVALOR_DECIMAL>",
  };

}
