/* Generated By:JavaCC: Do not edit this line. MiniLenguaje.java */
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import ClasesJava.*;
import java.util.ArrayList;

public class MiniLenguaje implements MiniLenguajeConstants {
  public static boolean verbose = false;

  public static Tabla_simbolos tabla_simbolos;

  public static int nivel;

  public static final int TBD = - 1;

  public static void main(String args []) throws ParseException, FileNotFoundException
  {
    for (int i = 0; i < args.length; i++)
    {
      if (args [i].equals("-v"))
      verbose = true;
    }
    //MiniLenguaje parser = new MiniLenguaje(System.in);
    FileInputStream file = null;
    try
    {
      file = new FileInputStream(args [0]);
      MiniLenguaje parser = new MiniLenguaje(file);
    }
    catch (FileNotFoundException e)
    {
      // TODO: Explicar instrucciones de ejecución
      System.err.print("ERROR: No se ha podido encontrar el archivo: " + args [0]);
      System.exit(- 1);
    }
    catch (ArrayIndexOutOfBoundsException e)
    {
      // TODO: Explicar instrucciones de ejecución
      System.err.print("ERROR: No se ha especificado un archivo");
      System.exit(- 1);
    }
    try
    {
      MiniLenguaje.programa(verbose);
    }
    catch (ParseException e)
    {
      System.err.println("Desde parse exception");
      System.err.println(e.getMessage());
      e.printStackTrace();
      //MiniLenguaje.ReInit(System.in);
    }
    catch (Error e)
    {
      e.printStackTrace();
      System.err.println(e.getMessage());
      System.exit(0);
    }
  }

  /**
* Código obtenido de https://stackoverflow.com/questions/29127861/dont-stop-parsing-after-first-exception
*/
  private static void error_skipto(int kind)
  {
    //ParseException e = generateParseException();
    //System.out.println(e.toString());    
    Token t = token;
    while (t.kind != kind && t.kind != EOF)
    {
      t = getNextToken();
    }
  }

  private static void error_skipto(int kind1, int kind2)
  {
    //ParseException e = generateParseException();
    //System.out.println(e.toString());    
    Token t;
    do
    {
      t = getNextToken();
    }
    while (t.kind != kind1 && t.kind != kind2 && t.kind != EOF);
  }

  private static void error_sintactico(ParseException e)
  {
    //error_sintactico(e, "");
    System.err.println("ERROR SINTACTICO: " + e.getMessage());
    e.printStackTrace();
    //Token lastRead = MiniLenguaje.getNextToken();
    error_skipto(tFIN_SENTENCIA, tFIN);
  }

  private static void error_sintactico(ParseException e, String msg)
  {
    //correcto = false;
    //Token lastRead = MiniLenguaje.getNextToken();
    //System.err.println("ERROR SINTACTICO (<" + lastRead.beginLine + ", " + 
    //lastRead.beginColumn + ">) : <Simbolo obtenido: '" + lastRead.image + 
    //"'. " + msg + ">");
  }

  private static void error_semantico(Exception e)
  {
    System.err.println(e);
  }

  private static void error_semantico(String e)
  {
    System.err.println(new SemanticException(token, e));
  }

  private static RegistroExpr comprobacionExpresion(RegistroExpr r1, RegistroExpr r2, String operador)
  {
    RegistroExpr resultado = new RegistroExpr();
    if ((r1.tipo != Tipo_variable.DESCONOCIDO) && (r2.tipo != Tipo_variable.DESCONOCIDO) &&
    (r1.tipo != r2.tipo))
    {
      error_semantico("Los operandos deben ser del mismo tipo");
      resultado = new RegistroExpr(Tipo_variable.DESCONOCIDO);
    }
    else if ((r1.tipo != Tipo_variable.DESCONOCIDO) && (r2.tipo != Tipo_variable.DESCONOCIDO) &&
    (r1.tipo == r2.tipo))
    {
      resultado = new RegistroExpr(r1, r2, operador);
    }
    return resultado;
  }

/************************************
************* PROGRAMA **************
*************************************/

// <tPROGRAMA> <tIDENTIFICADOR> <tFIN_SENTENCIA> declaracion_variables() declaracion_acciones() bloque_sentencias()
  static final public void programa(boolean verbose) throws ParseException {
    tabla_simbolos = Tabla_simbolos.inicializar_tabla(31);
    nivel = 0;
    jj_consume_token(tPROGRAMA);
    jj_consume_token(tIDENTIFICADOR);
    tabla_simbolos.introducir_programa(token.image, TBD);
    jj_consume_token(tFIN_SENTENCIA);
    declaracion_variables();
    System.out.println("Fin de declaracion de variables");
    declaracion_acciones();
    System.out.println("Fin de declaracion de acciones");
    bloque_sentencias();
    tabla_simbolos.eliminar_programa();
    System.out.println("Fin de programa");
    jj_consume_token(0);
  }

// (declaracion()<tFIN_SENTENCIA>)*
  static final public void declaracion_variables() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tENTERO:
      case tDECIMAL:
      case tBOOLEANO:
      case tCARACTER:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      try {
        declaracion();
        jj_consume_token(tFIN_SENTENCIA);
      } catch (ParseException e) {
      error_sintactico(e);
      declaracion_variables();
      }
    }
  }

// tipo_variables() identificadores()
  static final public void declaracion() throws ParseException {
  Tipo_variable tipo;
  ArrayList < String > identificadores;
    try {
      tipo = tipo_variables();
      identificadores = identificadores();
      for (String identificador : identificadores)
      {
        if (tabla_simbolos.introducir_variable(identificador, tipo, nivel, TBD) == null)
        {
          error_semantico(new ExcepcionTablaSimbolos(identificador, token.beginLine, nivel, tabla_simbolos.buscar_simbolo(identificador)));
        }
      }
    } catch (ParseException e) {
    error_sintactico(e);
    }
  }

// <tENTERO> | <tCARACTER> | <tBOOLEANO> | <tDECIMAL>
  static final public Tipo_variable tipo_variables() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tENTERO:
      jj_consume_token(tENTERO);
    {if (true) return Tipo_variable.ENTERO;}
      break;
    case tCARACTER:
      jj_consume_token(tCARACTER);
    {if (true) return Tipo_variable.CHAR;}
      break;
    case tBOOLEANO:
      jj_consume_token(tBOOLEANO);
    {if (true) return Tipo_variable.BOOLEANO;}
      break;
    case tDECIMAL:
      jj_consume_token(tDECIMAL);
    {if (true) return Tipo_variable.DECIMAL;}
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

// <tIDENTIFICADOR>(<tCOMA><tIDENTIFICADOR>)*
  static final public ArrayList < String > identificadores() throws ParseException {
  ArrayList < String > identificadores = new ArrayList();
    try {
      jj_consume_token(tIDENTIFICADOR);
      identificadores.add(token.image);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tCOMA:
          ;
          break;
        default:
          jj_la1[2] = jj_gen;
          break label_2;
        }
        jj_consume_token(tCOMA);
        jj_consume_token(tIDENTIFICADOR);
      identificadores.add(token.image);
      }
      {if (true) return identificadores;}
    } catch (ParseException e) {
    error_sintactico(e);
    {if (true) return identificadores;}
    }
    throw new Error("Missing return statement in function");
  }

// (declaracion_accion())*
  static final public void declaracion_acciones() throws ParseException {
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tACCION:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_3;
      }
      try {
        declaracion_accion();
      } catch (ParseException e) {
      error_sintactico(e);
      declaracion_acciones();
      }
    }
  }

// cabecera_accion() <tFIN_SENTENCIA> declaracion_variables() declaracion_acciones() bloque_sentencias()
  static final public void declaracion_accion() throws ParseException {
    try {
      cabecera_accion();
      jj_consume_token(tFIN_SENTENCIA);
      declaracion_variables();
      declaracion_acciones();
      bloque_sentencias();
    } catch (ParseException e) {
    error_sintactico(e);
    }
  }

// <tACCION> <tIDENTIFICADOR> parametros_formales()
  static final public void cabecera_accion() throws ParseException {
  ArrayList < Simbolo > parametros;
  Simbolo accion;
    try {
      jj_consume_token(tACCION);
      jj_consume_token(tIDENTIFICADOR);
      accion = tabla_simbolos.introducir_accion(token.image, nivel, TBD);
      if (accion == null)
      {
        error_semantico(new ExcepcionTablaSimbolos(token, nivel, tabla_simbolos.buscar_simbolo(token.image)));
      }
      nivel++;
      System.out.println("Aumenta nivel accion: " + accion.getNombre() + " nivel: " + nivel);
      parametros = parametros_formales();
      for (Simbolo parametro : parametros)
      {
        accion.introducir_parametro(parametro);
      }
    } catch (ParseException e) {
    error_sintactico(e);
    }
  }

// ((<tPARENTESIS_IZQ> parametros()) (<tFIN_SENTENCIA> parametros())* <tPARENTESIS_DCHA>)? 
  static final public ArrayList < Simbolo > parametros_formales() throws ParseException {
  if (MiniLenguaje.verbose) System.out.println("Parametros formales \u005cn");
  ArrayList < Simbolo > parametros = new ArrayList < Simbolo > ();
  ArrayList < Simbolo > masParametros;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tPARENTESIS_IZQ:
        jj_consume_token(tPARENTESIS_IZQ);
        parametros = parametros();
        label_4:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case tFIN_SENTENCIA:
            ;
            break;
          default:
            jj_la1[4] = jj_gen;
            break label_4;
          }
          jj_consume_token(tFIN_SENTENCIA);
          masParametros = parametros();
      parametros.addAll(masParametros);
        }
        jj_consume_token(tPARENTESIS_DCHA);
        break;
      default:
        jj_la1[5] = jj_gen;
        ;
      }
      {if (true) return parametros;}
    } catch (ParseException e) {
    error_sintactico(e);
    {if (true) return parametros;}
    }
    throw new Error("Missing return statement in function");
  }

// expresion() (<tCOMA> expresion())*
  static final public ArrayList < Simbolo > lista_parametros(Clase_parametro clase, Tipo_variable tipo) throws ParseException {
  ArrayList < String > identificadores;
  ArrayList < Simbolo > parametros = new ArrayList();
  Simbolo parametro;
    try {
      identificadores = identificadores();
      for (String identificador : identificadores)
      {
        parametro = tabla_simbolos.introducir_parametro(identificador, tipo, clase, nivel, TBD);
        if (parametro == null)
        {
          error_semantico(new ExcepcionTablaSimbolos(identificador, token.beginLine, nivel, tabla_simbolos.buscar_simbolo(identificador)));
        }
        else
        {
          parametros.add(parametro);
        }
      }
      {if (true) return parametros;}
    } catch (ParseException e) {
    error_sintactico(e);
    {if (true) return parametros;}
    }
    throw new Error("Missing return statement in function");
  }

// clase_parametros() tipo_variables() lista_parametros()
  static final public ArrayList < Simbolo > parametros() throws ParseException {
  Clase_parametro clase;
  Tipo_variable tipo;
  ArrayList < Simbolo > parametros = new ArrayList();
    try {
      clase = clase_parametros();
      tipo = tipo_variables();
      parametros = lista_parametros(clase, tipo);
      {if (true) return parametros;}
    } catch (ParseException e) {
    error_sintactico(e);
    {if (true) return parametros;}
    }
    throw new Error("Missing return statement in function");
  }

// <tVAL> | <tREF>
  static final public Clase_parametro clase_parametros() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tVAL:
      jj_consume_token(tVAL);
    {if (true) return Clase_parametro.VAL;}
      break;
    case tREF:
      jj_consume_token(tREF);
    {if (true) return Clase_parametro.REF;}
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

// <tPRINCIPIO> lista_sentencias() <tFIN>
  static final public void bloque_sentencias() throws ParseException {
    try {
      jj_consume_token(tPRINCIPIO);
      lista_sentencias();
      jj_consume_token(tFIN);
      //System.out.println("######################################################################################");    
      //System.out.println("Tabla antes de borrar nivel " + nivel);
      //System.out.println(tabla_simbolos);
      tabla_simbolos.ocultar_parametros(nivel);
      tabla_simbolos.eliminar_variables(nivel);
      // Elimino los parámetros ocultos al eliminar las acciones
      tabla_simbolos.eliminar_acciones(nivel);
      nivel--;
      //System.out.println("\nTabla despues de borrar nivel " + (nivel + 1));
      //System.out.println(tabla_simbolos);
      //System.out.println("######################################################################################");

    } catch (ParseException e) {
    error_sintactico(e);
    lista_sentencias();
    }
  }

// (sentencia())* 
  static final public void lista_sentencias() throws ParseException {
    label_5:
    while (true) {
      try {
        sentencia();
      } catch (ParseException e) {
      error_sintactico(e);
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tSI:
      case tMQ:
      case tESCRIBIR:
      case tLEER:
      case tIDENTIFICADOR:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_5;
      }
    }
  }

/*
leer()  < tFIN_SENTENCIA >|
  escribir() < tFIN_SENTENCIA >|
  < tIDENTIFICADOR > [asignacion() |  invocacion_accion() ] < tFIN_SENTENCIA > |
  seleccion()  |
  mientras_que()
  */
  static final public void sentencia() throws ParseException {
  Token identificador;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tLEER:
        leer();
        jj_consume_token(tFIN_SENTENCIA);
        break;
      case tESCRIBIR:
        escribir();
        jj_consume_token(tFIN_SENTENCIA);
        break;
      case tIDENTIFICADOR:
        identificador = jj_consume_token(tIDENTIFICADOR);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tPARENTESIS_IZQ:
        case tOPAS:
        case tFIN_SENTENCIA:
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case tOPAS:
            asignacion(identificador);
            break;
          case tPARENTESIS_IZQ:
          case tFIN_SENTENCIA:
            invocacion_accion(identificador);
            break;
          default:
            jj_la1[8] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
        default:
          jj_la1[9] = jj_gen;
          ;
        }
        break;
      case tSI:
        seleccion();
        break;
      case tMQ:
        mientras_que();
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    error_sintactico(e);
    }
  }

// <tLEER> <tPARENTESIS_IZQ> lista_asignables() <tPARENTESIS_DCHA>
  static final public void leer() throws ParseException {
  ArrayList < Token > asignables = new ArrayList();
  Simbolo s;
    try {
      jj_consume_token(tLEER);
      jj_consume_token(tPARENTESIS_IZQ);
      asignables = lista_asignables();
      jj_consume_token(tPARENTESIS_DCHA);
      for (Token t : asignables)
      {
        s = tabla_simbolos.buscar_simbolo(t.image);
        if (s == null)
        {
          error_semantico("Identificador desconocido: " + t.image );
          tabla_simbolos.introducir_variable(t.image, Tipo_variable.DESCONOCIDO, nivel, TBD);
        }
        else if (s.getVariable() != Tipo_variable.CHAR
        && s.getVariable() != Tipo_variable.ENTERO
        && s.getVariable() != Tipo_variable.DESCONOCIDO)
        {
          error_semantico("No se puede asignar la variable " + t.image + " ya que es de tipo " + s.getVariable());
        }
        else if (s.esParametro() && s.esValor())
        {
          error_semantico("No se puede asignar " + t.image + " ya que es un parametro por valor");
        }
      }
    } catch (ParseException e) {
    error_sintactico(e);
    }
  }

// <tIDENTIFICADOR> (<tCOMA> <tIDENTIFICADOR>)*
  static final public ArrayList < Token > lista_asignables() throws ParseException {
  ArrayList < Token > asignables = new ArrayList();
  Token t;
    try {
      t = jj_consume_token(tIDENTIFICADOR);
      asignables.add(t);
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tCOMA:
          ;
          break;
        default:
          jj_la1[11] = jj_gen;
          break label_6;
        }
        jj_consume_token(tCOMA);
        t = jj_consume_token(tIDENTIFICADOR);
      asignables.add(t);
      }
      {if (true) return asignables;}
    } catch (ParseException e) {
    error_sintactico(e);
    {if (true) return asignables;}
    }
    throw new Error("Missing return statement in function");
  }

// <tESCRIBIR> <tPARENTESIS_IZQ> lista_escribibles() <tPARENTESIS_DCHA>
  static final public void escribir() throws ParseException {
 ArrayList<RegistroExpr > escribibles = new ArrayList();
    try {
      jj_consume_token(tESCRIBIR);
      jj_consume_token(tPARENTESIS_IZQ);
      escribibles = lista_escribibles();
      jj_consume_token(tPARENTESIS_DCHA);
    } catch (ParseException e) {
    error_sintactico(e);
    }
  }

// expresion() (<tCOMA> expresion())*
  static final public ArrayList<RegistroExpr > lista_escribibles() throws ParseException {
  ArrayList < RegistroExpr > escribibles = new ArrayList();
  RegistroExpr r;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tNOT:
      case tTRUE:
      case tFALSE:
      case tENTACAR:
      case tCARAENT:
      case tPARENTESIS_IZQ:
      case tMENOS:
      case tCHAR:
      case tIDENTIFICADOR:
      case tVALOR_ENTERO:
      case tVALOR_DECIMAL:
        r = expresion();
      escribibles.add(r);
        break;
      case tSTRING:
        jj_consume_token(tSTRING);
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tCOMA:
          ;
          break;
        default:
          jj_la1[13] = jj_gen;
          break label_7;
        }
        jj_consume_token(tCOMA);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tNOT:
        case tTRUE:
        case tFALSE:
        case tENTACAR:
        case tCARAENT:
        case tPARENTESIS_IZQ:
        case tMENOS:
        case tCHAR:
        case tIDENTIFICADOR:
        case tVALOR_ENTERO:
        case tVALOR_DECIMAL:
          r = expresion();
      escribibles.add(r);
          break;
        case tSTRING:
          jj_consume_token(tSTRING);
          break;
        default:
          jj_la1[14] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      {if (true) return escribibles;}
    } catch (ParseException e) {
    error_sintactico(e);
    {if (true) return escribibles;}
    }
    throw new Error("Missing return statement in function");
  }

// <tOPAS> expresion() 
  static final public void asignacion(Token t) throws ParseException {
  Simbolo s;
  RegistroExpr r;
  Tipo_variable tipoID;
    try {
      s = tabla_simbolos.buscar_simbolo(t.image);
      if (s == null)
      {
        error_semantico("Identificador desconocido en la parte izquierda de la asignacion: " + t.image);
        tipoID = Tipo_variable.DESCONOCIDO;
        tabla_simbolos.introducir_variable(t.image, Tipo_variable.DESCONOCIDO, nivel, TBD);
      }
      else
      {
        if (s.esParametro() && s.esValor())
        {
          error_semantico("No se puede realizar una asignacion a un parametro por valor");
        }
        tipoID = s.getVariable();
      }
      jj_consume_token(tOPAS);
      r = expresion();
      if ((tipoID != Tipo_variable.DESCONOCIDO) && (r.tipo != Tipo_variable.DESCONOCIDO) && (tipoID != r.tipo))
      {
        error_semantico("Tipos incompatibles en la asignacion");
      }
      jj_consume_token(tFIN_SENTENCIA);
    } catch (ParseException e) {
    error_sintactico(e);
    }
  }

// argumentos() 
  static final public void invocacion_accion(Token t) throws ParseException {
  Simbolo accion, paramOriginal;
  ArrayList < RegistroExpr > args = new ArrayList();
  RegistroExpr param;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tPARENTESIS_IZQ:
        args = argumentos();
        break;
      default:
        jj_la1[15] = jj_gen;
        ;
      }
      jj_consume_token(tFIN_SENTENCIA);
      accion = tabla_simbolos.buscar_simbolo(t.image);
      if (accion == null)
      {
        error_semantico("Identificador de accion desconocido");
        accion = tabla_simbolos.introducir_accion(t.image, nivel, TBD);
        accion.setVariable(Tipo_variable.DESCONOCIDO);
      }
      else if (!accion.esAccion())
      {
        error_semantico(t.image + " no es una accion");
      }
      else if (accion.getVariable() != Tipo_variable.DESCONOCIDO)
      {
        if (args.size() != accion.getListaParametros().size())
        {
          error_semantico("El numero de parametros no coincide con el de la accion " +
          t.image + ", se han proporcionado " + args.size() + " pero se requieren " + accion.getListaParametros().size());
        }
        else
        {
          for (int i = 0; i < args.size(); i++)
          {
            // TODO: Comprobar tipo de los parametros
            paramOriginal = accion.getListaParametros().get(i);
            param = args.get(i);
          }
        }
      }
    } catch (ParseException e) {
    error_sintactico(e);
    }
  }

// <tMQ> expresion() lista_sentencias() <tFMQ>
  static final public void mientras_que() throws ParseException {
  RegistroExpr r;
    try {
      jj_consume_token(tMQ);
      r = expresion();
      if (r.tipo != Tipo_variable.DESCONOCIDO && r.tipo != Tipo_variable.BOOLEANO)
      {
        error_semantico("La condicion en el mientras_que debe ser un booleano");
      }
      else if (r.tipo == Tipo_variable.BOOLEANO && r.valorBool != null)
      {
        if (r.valorBool == true)
        {
          error_semantico("Bucle infinito");
        }
        else
        {
          error_semantico("Nunca se entra en el bucle");
        }
      }
      lista_sentencias();
      jj_consume_token(tFMQ);
    } catch (ParseException e) {
    error_sintactico(e);
    }
  }

// <tSI> expresion() <tENT> lista_sentencias() (<tSI_NO> lista_sentencias())?  <tFSI>
  static final public void seleccion() throws ParseException {
  RegistroExpr r;
    try {
      jj_consume_token(tSI);
      r = expresion();
      if (r.tipo != Tipo_variable.DESCONOCIDO && r.tipo != Tipo_variable.BOOLEANO)
      {
        error_semantico("La condicien la seleccion debe ser un booleano");
      }
      else if (r.tipo == Tipo_variable.BOOLEANO && r.valorBool != null)
      {
        if (r.valorBool == true)
        {
          error_semantico("La condicion es siempre cierta");
        }
        else
        {
          error_semantico("La condicion nunca es cierta");
        }
      }
      jj_consume_token(tENT);
      lista_sentencias();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tSI_NO:
        jj_consume_token(tSI_NO);
        lista_sentencias();
        break;
      default:
        jj_la1[16] = jj_gen;
        ;
      }
      jj_consume_token(tFSI);
    } catch (ParseException e) {
    error_sintactico(e);
    }
  }

// <tPARENTESIS_IZQ> (lista_expresiones())? <tPARENTESIS_DCHA>
  static final public ArrayList < RegistroExpr > argumentos() throws ParseException {
  ArrayList < RegistroExpr > args = new ArrayList();
    try {
      jj_consume_token(tPARENTESIS_IZQ);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tNOT:
      case tTRUE:
      case tFALSE:
      case tENTACAR:
      case tCARAENT:
      case tPARENTESIS_IZQ:
      case tMENOS:
      case tCHAR:
      case tIDENTIFICADOR:
      case tVALOR_ENTERO:
      case tVALOR_DECIMAL:
        args = lista_expresiones();
        break;
      default:
        jj_la1[17] = jj_gen;
        ;
      }
      jj_consume_token(tPARENTESIS_DCHA);
      {if (true) return args;}
    } catch (ParseException e) {
    error_sintactico(e);
    {if (true) return args;}
    }
    throw new Error("Missing return statement in function");
  }

// expresion() (<tCOMA> expresion())*
  static final public ArrayList < RegistroExpr > lista_expresiones() throws ParseException {
  ArrayList < RegistroExpr > args = new ArrayList();
  RegistroExpr r;
    try {
      r = expresion();
      args.add(r);
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tCOMA:
          ;
          break;
        default:
          jj_la1[18] = jj_gen;
          break label_8;
        }
        jj_consume_token(tCOMA);
        expresion();
      args.add(r);
      }
      {if (true) return args;}
    } catch (ParseException e) {
    error_sintactico(e);
    {if (true) return args;}
    }
    throw new Error("Missing return statement in function");
  }

// expresion_simple() (operador_relacional() expresion_simple())*
  static final public RegistroExpr expresion() throws ParseException {
  RegistroExpr r1, r2;
  Token token_operador;
  String operador;
    try {
      r1 = expresion_simple();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tIGUAL:
      case tMAI:
      case tMEI:
      case tNI:
      case tMAYOR:
      case tMENOR:
        token_operador = operador_relacional();
        r2 = expresion_simple();
      operador = token_operador.image;
      r1 = comprobacionExpresion(r1, r2, operador);
      /*switch (operador)
      {
        case "=" :         
        break;
        case "<>" :        
        break;
        case "<" : 
        break;
        case "<=" : 
        break;
        case ">" : 
        break;
        case ">=" : 
        break;
      }*/

        break;
      default:
        jj_la1[19] = jj_gen;
        ;
      }
      //System.out.println(r1);
      {if (true) return r1;}
    } catch (ParseException e) {
    error_sintactico(e);
    }
    throw new Error("Missing return statement in function");
  }

// <tMAYOR> | <tMENOR> | <tMAI> | <tMEI> | <tNI> | <tIGUAL>
  static final public Token operador_relacional() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tMAYOR:
      t = jj_consume_token(tMAYOR);
    {if (true) return t;}
      break;
    case tMENOR:
      t = jj_consume_token(tMENOR);
    {if (true) return t;}
      break;
    case tMAI:
      t = jj_consume_token(tMAI);
    {if (true) return t;}
      break;
    case tMEI:
      t = jj_consume_token(tMEI);
    {if (true) return t;}
      break;
    case tNI:
      t = jj_consume_token(tNI);
    {if (true) return t;}
      break;
    case tIGUAL:
      t = jj_consume_token(tIGUAL);
    {if (true) return t;}
      break;
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

// termino() (operador_aditivo() termino())*
  static final public RegistroExpr expresion_simple() throws ParseException {
  RegistroExpr r1 = new RegistroExpr();
  RegistroExpr r2 = new RegistroExpr();
  Token token_operador;
  String operador;
    try {
      r1 = termino();
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tOR:
        case tMAS:
        case tMENOS:
          ;
          break;
        default:
          jj_la1[21] = jj_gen;
          break label_9;
        }
        token_operador = operador_aditivo();
        r2 = termino();
      operador = token_operador.image;
      switch (operador)
      {
        case "+" :
        if ((r1.tipo != Tipo_variable.ENTERO) && (r1.tipo != Tipo_variable.DESCONOCIDO)
        || (r2.tipo != Tipo_variable.ENTERO) && (r2.tipo != Tipo_variable.DESCONOCIDO))
        {
          error_semantico("Tipo incompatible. Se esperaba entero.");
          r1 = new RegistroExpr(Tipo_variable.DESCONOCIDO);
        }
        else
        {
          r1 = new RegistroExpr(r1, r2, operador);
          if (r1.valorEnt != null && (r1.valorEnt >= Math.pow(2, 16) || r1.valorEnt < (- Math.pow(2, 16))))
          {
            error_semantico("Error de overflow/underflow al realizar la suma.");
            r1.valorEnt = null;
          }
        }
        break;
        case "-" :
        if ((r1.tipo != Tipo_variable.ENTERO) && (r1.tipo != Tipo_variable.DESCONOCIDO)
        || (r2.tipo != Tipo_variable.ENTERO) && (r2.tipo != Tipo_variable.DESCONOCIDO))
        {
          error_semantico("Tipo incompatible. Se esperaba entero.");
          r1 = new RegistroExpr(Tipo_variable.DESCONOCIDO);
        }
        else
        {
          r1 = new RegistroExpr(r1, r2, operador);
          if (r1.valorEnt != null && (r1.valorEnt >= Math.pow(2, 16) || r1.valorEnt < (- Math.pow(2, 16))))
          {
            error_semantico("Error de overflow/underflow al realizar la resta.");
            r1.valorEnt = null;
          }
        }
        break;
        case "or" :
        if ((r1.tipo != Tipo_variable.BOOLEANO) && (r1.tipo != Tipo_variable.DESCONOCIDO)
        || (r2.tipo != Tipo_variable.BOOLEANO) && (r2.tipo != Tipo_variable.DESCONOCIDO))
        {
          error_semantico("Tipo incompatible. Se esperaba booleano.");
          r1 = new RegistroExpr(Tipo_variable.DESCONOCIDO);
        }
        else
        {
          r1 = new RegistroExpr(r1, r2, operador);
        }
        break;
      }
      }
      {if (true) return r1;}
    } catch (ParseException e) {
    error_sintactico(e);
    {if (true) return r1;}
    }
    throw new Error("Missing return statement in function");
  }

// <tMAS> | <tMENOS> | <tOR>
  static final public Token operador_aditivo() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tMAS:
      t = jj_consume_token(tMAS);
    {if (true) return t;}
      break;
    case tMENOS:
      t = jj_consume_token(tMENOS);
    {if (true) return t;}
      break;
    case tOR:
      t = jj_consume_token(tOR);
    {if (true) return t;}
      break;
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

// factor() (operador_multiplicativo() factor())* 
  static final public RegistroExpr termino() throws ParseException {
  RegistroExpr r1 = new RegistroExpr(), r2 = new RegistroExpr();
  Token token_operador;
  String operador;
    try {
      r1 = factor();
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case tAND:
        case tMOD:
        case tPOR:
        case tDIV:
          ;
          break;
        default:
          jj_la1[23] = jj_gen;
          break label_10;
        }
        token_operador = operador_multiplicativo();
        r2 = factor();
      operador = token_operador.image;
      switch (operador)
      {
        case "*" :
        if ((r1.tipo != Tipo_variable.ENTERO) && (r1.tipo != Tipo_variable.DESCONOCIDO)
        || (r2.tipo != Tipo_variable.ENTERO) && (r2.tipo != Tipo_variable.DESCONOCIDO))
        {
          error_semantico("Tipo incompatible. Se esperaba entero.");
          r1 = new RegistroExpr(Tipo_variable.DESCONOCIDO);
        }
        else
        {
          r1 = new RegistroExpr(r1, r2, operador);
          if (r1.valorEnt != null && (r1.valorEnt >= Math.pow(2, 16) || r1.valorEnt < (- Math.pow(2, 16))))
          {
            error_semantico("Error de overflow/underflow al realizar la multiplicacion.");
            r1.valorEnt = null;
          }
        }
        break;
        case "div" :
        if ((r1.tipo != Tipo_variable.ENTERO) && (r1.tipo != Tipo_variable.DESCONOCIDO)
        || (r2.tipo != Tipo_variable.ENTERO) && (r2.tipo != Tipo_variable.DESCONOCIDO))
        {
          error_semantico("Tipo incompatible. Se esperaba entero.");
          r1 = new RegistroExpr(Tipo_variable.DESCONOCIDO);
        }
        else
        {
          if (r2.valorEnt != null && r2.valorEnt == 0)
          {
            error_semantico("Division por 0");
            r1 = new RegistroExpr(Tipo_variable.DESCONOCIDO);
          }
          else
          {
            r1 = new RegistroExpr(r1, r2, operador);
          }
        }
        break;
        case "/" :
        if ((r1.tipo != Tipo_variable.ENTERO) && (r1.tipo != Tipo_variable.DESCONOCIDO)
        || (r2.tipo != Tipo_variable.ENTERO) && (r2.tipo != Tipo_variable.DESCONOCIDO))
        {
          error_semantico("Tipo incompatible. Se esperaba entero.");
          r1 = new RegistroExpr(Tipo_variable.DESCONOCIDO);
        }
        else
        {
          if (r2.valorEnt != null && r2.valorEnt == 0)
          {
            error_semantico("Division por 0");
            r1 = new RegistroExpr(Tipo_variable.DESCONOCIDO);
          }
          else
          {
            r1 = new RegistroExpr(r1, r2, operador);
          }
        }
        break;
        case "mod" :
        if ((r1.tipo != Tipo_variable.ENTERO) && (r1.tipo != Tipo_variable.DESCONOCIDO)
        || (r2.tipo != Tipo_variable.ENTERO) && (r2.tipo != Tipo_variable.DESCONOCIDO))
        {
          error_semantico("Tipo incompatible. Se esperaba entero.");
          r1 = new RegistroExpr(Tipo_variable.DESCONOCIDO);
        }
        else
        {
          if (r2.valorEnt != null && r2.valorEnt == 0)
          {
            error_semantico("Modulo por 0");
            r1 = new RegistroExpr(Tipo_variable.DESCONOCIDO);
          }
          else
          {
            r1 = new RegistroExpr(r1, r2, operador);
          }
        }
        break;
        case "and" :
        if ((r1.tipo != Tipo_variable.BOOLEANO) && (r1.tipo != Tipo_variable.DESCONOCIDO)
        || (r2.tipo != Tipo_variable.BOOLEANO) && (r2.tipo != Tipo_variable.DESCONOCIDO))
        {
          error_semantico("Tipo incompatible. Se esperaba booleano.");
          r1 = new RegistroExpr(Tipo_variable.DESCONOCIDO);
        }
        else
        {
          r1 = new RegistroExpr(r1, r2, operador);
        }
        break;
      }
      }
      {if (true) return r1;}
    } catch (ParseException e) {
    error_sintactico(e);
    {if (true) return r1;}
    }
    throw new Error("Missing return statement in function");
  }

// <tPOR> | <tDIV> | <tMOD> | <tAND>
  static final public Token operador_multiplicativo() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tPOR:
      t = jj_consume_token(tPOR);
    {if (true) return t;}
      break;
    case tDIV:
      t = jj_consume_token(tDIV);
    {if (true) return t;}
      break;
    case tMOD:
      t = jj_consume_token(tMOD);
    {if (true) return t;}
      break;
    case tAND:
      t = jj_consume_token(tAND);
    {if (true) return t;}
      break;
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/*
	< tMENOS > factor()
| < tNOT > factor()
| < tPARENTESIS_IZQ > expresion() < tPARENTESIS_DCHA >
| < tENTACAR > <tPARENTESIS_IZQ > expresion() < tPARENTESIS_DCHA >
| < tCARAENT > <tPARENTESIS_IZQ > expresion() < tPARENTESIS_DCHA >
| < tIDENTIFICADOR >
| < tVALOR_ENTERO >
| < tVALOR_DECIMAL >
| < tSTRING >
| < tTRUE >
| < tFALSE >
*/
  static final public RegistroExpr factor() throws ParseException {
  RegistroExpr rExpr = new RegistroExpr();
  Token t;
  Simbolo s;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case tMENOS:
        jj_consume_token(tMENOS);
        rExpr = factor();
      if ((rExpr.tipo != Tipo_variable.ENTERO) && (rExpr.tipo != Tipo_variable.DESCONOCIDO))
      {
        error_semantico(new ExcepcionTipo(token, rExpr.tipo, Tipo_variable.ENTERO));
        rExpr.tipo = Tipo_variable.ENTERO;
      }
      if (rExpr.valorEnt != null)
      {
        rExpr.valorEnt = - rExpr.valorEnt;
      }
      {if (true) return rExpr;}
        break;
      case tNOT:
        jj_consume_token(tNOT);
        rExpr = factor();
      if ((rExpr.tipo != Tipo_variable.BOOLEANO) && (rExpr.tipo != Tipo_variable.DESCONOCIDO))
      {
        error_semantico(new ExcepcionTipo(token, rExpr.tipo, Tipo_variable.BOOLEANO));
        rExpr.tipo = Tipo_variable.BOOLEANO;
      }
      if (rExpr.valorBool != null)
      {
        rExpr.valorBool = !rExpr.valorBool;
      }
      {if (true) return rExpr;}
        break;
      case tPARENTESIS_IZQ:
        jj_consume_token(tPARENTESIS_IZQ);
        rExpr = expresion();
        jj_consume_token(tPARENTESIS_DCHA);
      {if (true) return rExpr;}
        break;
      case tENTACAR:
        jj_consume_token(tENTACAR);
        jj_consume_token(tPARENTESIS_IZQ);
        rExpr = expresion();
        jj_consume_token(tPARENTESIS_DCHA);
      if ((rExpr.tipo != Tipo_variable.ENTERO) && (rExpr.tipo != Tipo_variable.DESCONOCIDO))
      {
        error_semantico(new ExcepcionTipo(token, rExpr.tipo, Tipo_variable.ENTERO));
      }
      if ((rExpr.valorEnt != null) && ((rExpr.valorEnt > 255) || (rExpr.valorEnt < 0)))
      {
        error_semantico("La expresion no se puede convertir en un caracter valido");
      }
      rExpr.tipo = Tipo_variable.CHAR;
      {if (true) return rExpr;}
        break;
      case tCARAENT:
        jj_consume_token(tCARAENT);
        jj_consume_token(tPARENTESIS_IZQ);
        rExpr = expresion();
        jj_consume_token(tPARENTESIS_DCHA);
      if ((rExpr.tipo != Tipo_variable.CHAR) && (rExpr.tipo != Tipo_variable.DESCONOCIDO))
      {
        error_semantico(new ExcepcionTipo(token, rExpr.tipo, Tipo_variable.CHAR));
      }
      rExpr.tipo = Tipo_variable.ENTERO;
      {if (true) return rExpr;}
        break;
      case tIDENTIFICADOR:
        t = jj_consume_token(tIDENTIFICADOR);
      s = tabla_simbolos.buscar_simbolo(t.image);
      rExpr = new RegistroExpr();
      if (s == null)
      {
        error_semantico("Identificador desconocido: " + t.image);
        tabla_simbolos.introducir_variable(token.image, Tipo_variable.DESCONOCIDO, nivel, TBD);
        rExpr.tipo = Tipo_variable.DESCONOCIDO;
      }
      else
      {
        rExpr.tipo = s.getVariable();
      }
      rExpr.parametro = Clase_parametro.REF;
      {if (true) return rExpr;}
        break;
      case tVALOR_ENTERO:
        t = jj_consume_token(tVALOR_ENTERO);
      rExpr = new RegistroExpr();
      rExpr.valorEnt = Integer.parseInt(t.image);
      rExpr.tipo = Tipo_variable.ENTERO;
      {if (true) return rExpr;}
        break;
      case tVALOR_DECIMAL:
        t = jj_consume_token(tVALOR_DECIMAL);
      rExpr = new RegistroExpr();
      rExpr.valorDecimal = Float.parseFloat(t.image);
      rExpr.tipo = Tipo_variable.DECIMAL;
      {if (true) return rExpr;}
        break;
      case tCHAR:
        t = jj_consume_token(tCHAR);
      rExpr = new RegistroExpr();
      rExpr.valorChar = t.image;
      rExpr.tipo = Tipo_variable.CHAR;
      {if (true) return rExpr;}
        break;
      case tTRUE:
        t = jj_consume_token(tTRUE);
      rExpr = new RegistroExpr();
      rExpr.valorBool = true;
      rExpr.tipo = Tipo_variable.BOOLEANO;
      {if (true) return rExpr;}
        break;
      case tFALSE:
        t = jj_consume_token(tFALSE);
      rExpr = new RegistroExpr();
      rExpr.valorBool = false;
      rExpr.tipo = Tipo_variable.BOOLEANO;
      {if (true) return rExpr;}
        break;
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    error_sintactico(e);
    {if (true) return rExpr;}
    }
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public MiniLenguajeTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[26];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x0,0x0,0x80000000,0x0,0x0,0x0,0x3440000,0x0,0x0,0x3440000,0x0,0x78008000,0x0,0x78008000,0x0,0x100000,0x78008000,0x0,0x0,0x0,0x4000,0x4000,0x4002000,0x4002000,0x78008000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x3c,0x3c,0x8000,0x0,0x4000,0x100,0x3,0x20000000,0x5100,0x5100,0x20000000,0x8000,0xf8020100,0x8000,0xf8020100,0x100,0x0,0xe8020100,0x8000,0x1f02000,0x1f02000,0x30000,0x30000,0xc0000,0xc0000,0xe8020100,};
   }

  /** Constructor with InputStream. */
  public MiniLenguaje(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniLenguaje(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MiniLenguajeTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public MiniLenguaje(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new MiniLenguajeTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public MiniLenguaje(MiniLenguajeTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(MiniLenguajeTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[64];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 26; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 64; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
