/* Generated By:JavaCC: Do not edit this line. MiniLenguajeConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniLenguajeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tCLASE = 11;
  /** RegularExpression Id. */
  int tMETODO = 12;
  /** RegularExpression Id. */
  int tPROGRAMA = 13;
  /** RegularExpression Id. */
  int tVAR = 14;
  /** RegularExpression Id. */
  int tAND = 15;
  /** RegularExpression Id. */
  int tOR = 16;
  /** RegularExpression Id. */
  int tNOT = 17;
  /** RegularExpression Id. */
  int tPRINCIPIO = 18;
  /** RegularExpression Id. */
  int tFIN = 19;
  /** RegularExpression Id. */
  int tSI = 20;
  /** RegularExpression Id. */
  int tENT = 21;
  /** RegularExpression Id. */
  int tSI_NO = 22;
  /** RegularExpression Id. */
  int tFSI = 23;
  /** RegularExpression Id. */
  int tMQ = 24;
  /** RegularExpression Id. */
  int tFMQ = 25;
  /** RegularExpression Id. */
  int tESCRIBIR = 26;
  /** RegularExpression Id. */
  int tLEER = 27;
  /** RegularExpression Id. */
  int tMOD = 28;
  /** RegularExpression Id. */
  int tTRUE = 29;
  /** RegularExpression Id. */
  int tFALSE = 30;
  /** RegularExpression Id. */
  int tENTACAR = 31;
  /** RegularExpression Id. */
  int tCARAENT = 32;
  /** RegularExpression Id. */
  int tACCION = 33;
  /** RegularExpression Id. */
  int tVAL = 34;
  /** RegularExpression Id. */
  int tREF = 35;
  /** RegularExpression Id. */
  int tENTERO = 36;
  /** RegularExpression Id. */
  int tDECIMAL = 37;
  /** RegularExpression Id. */
  int tBOOLEANO = 38;
  /** RegularExpression Id. */
  int tCARACTER = 39;
  /** RegularExpression Id. */
  int tLLAVE_IZQ = 40;
  /** RegularExpression Id. */
  int tLLAVE_DCHA = 41;
  /** RegularExpression Id. */
  int tPARENTESIS_IZQ = 42;
  /** RegularExpression Id. */
  int tPARENTESIS_DCHA = 43;
  /** RegularExpression Id. */
  int tCORCHETE_IZQ = 44;
  /** RegularExpression Id. */
  int tCORCHETE_DCHA = 45;
  /** RegularExpression Id. */
  int tOPAS = 46;
  /** RegularExpression Id. */
  int tIGUAL = 47;
  /** RegularExpression Id. */
  int tFIN_SENTENCIA = 48;
  /** RegularExpression Id. */
  int tCOMA = 49;
  /** RegularExpression Id. */
  int tMAS = 50;
  /** RegularExpression Id. */
  int tMENOS = 51;
  /** RegularExpression Id. */
  int tPOR = 52;
  /** RegularExpression Id. */
  int tDIV = 53;
  /** RegularExpression Id. */
  int tMAI = 54;
  /** RegularExpression Id. */
  int tMEI = 55;
  /** RegularExpression Id. */
  int tNI = 56;
  /** RegularExpression Id. */
  int tMAYOR = 57;
  /** RegularExpression Id. */
  int tMENOR = 58;
  /** RegularExpression Id. */
  int tCHAR = 61;
  /** RegularExpression Id. */
  int tSTRING = 62;
  /** RegularExpression Id. */
  int tIDENTIFICADOR = 63;
  /** RegularExpression Id. */
  int tVALOR_ENTERO = 64;
  /** RegularExpression Id. */
  int tVALOR_DECIMAL = 65;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMENT = 1;
  /** Lexical state. */
  int COMENT_MULTI = 2;
  /** Lexical state. */
  int STRING = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"\\n\"",
    "<token of kind 8>",
    "\"%%\"",
    "<token of kind 10>",
    "\"clase\"",
    "\"metodo\"",
    "\"programa\"",
    "\"var\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"principio\"",
    "\"fin\"",
    "\"si\"",
    "\"ent\"",
    "\"si_no\"",
    "\"fsi\"",
    "\"mq\"",
    "\"fmq\"",
    "\"escribir\"",
    "\"leer\"",
    "\"mod\"",
    "\"true\"",
    "\"false\"",
    "\"entacar\"",
    "\"caraent\"",
    "\"accion\"",
    "\"val\"",
    "\"ref\"",
    "\"entero\"",
    "\"decimal\"",
    "\"booleano\"",
    "\"caracter\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\":=\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "<tDIV>",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\">\"",
    "\"<\"",
    "\"\\\"\"",
    "\"\\\"\"",
    "<tCHAR>",
    "<tSTRING>",
    "<tIDENTIFICADOR>",
    "<tVALOR_ENTERO>",
    "<tVALOR_DECIMAL>",
  };

}
